# fly.toml app configuration file generated for stylegenie on 2024-01-26T22:10:41+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'stylegenie'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 4
  memory_mb = 4096
